//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleComprobante
    {
        public long IdDetalleComprobante { get; set; }
        public int Numero { get; set; }
        public string Glosa { get; set; }
        public double MontoDebe { get; set; }
        public double MontoHaber { get; set; }
        public double MontoDebeAlt { get; set; }
        public double MontoHaberAlt { get; set; }
        public long IdUsuario { get; set; }
        public long IdComprobante { get; set; }
        public long IdCuenta { get; set; }
    
        public virtual Comprobante Comprobante { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
