//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public long IdArticulo { get; set; }
        public long NroLote { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int Cantidad { get; set; }
        public double PrecioCompra { get; set; }
        public int Stock { get; set; }
        public int Estado { get; set; }
        public long IdNota { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Nota Nota { get; set; }
    }
}
